title: Nilesh Raut
description: My Personal Blog
author: Nilesh Raut
logo: /upgrad_blog/static/img/avatar.png
github: https://github.com
about: Developer

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: id_analitics
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
